config/routes.rb
Rails.application.routes.draw do
  get 'movie/list'

  get 'recommendation/action'

  get 'movie/list_category'
  
  get 'movie/list_complete'
  
  get 'movie/delete_complete/:id' => 'movie#delete_complete'
  
  get 'movie/delete_movie'

  get "movie/show/:id" => 'movie#show'
  
  post "movie/write_review_complete"
  
  get 'recommendation/index'
  
  get 'movie/delete_review_complete/:id' => 'movie#delete_review_complete'

  get 'movie/liked_complete/:id' => 'movie#liked_complete'
  
  get 'movie/liked_delete_complete/:id' => 'movie#liked_delete_complete'

  get "movie/edit/:id" => 'movie#edit'
  
  get "user/mypage/:id" => 'user#mypage'

  get 'movie/write'

  post 'movie/write_complete'

  get 'movie/edit'

  post 'movie/edit_complete'
  
  
  get 'movie/get_movie'

  get 'comments/create'

  get 'comments/destroy'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :bulletins do
    resources :posts
  end
  get 'home/index'
  get 'user/signup'
  post "user/signup_complete"
  get "user/login"
  post "user/login_complete"
  get "user/logout_complete"

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :bulletin
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :login_check
  before_action :set_bulletin
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = @bulletin.posts.all
  end

  def show
  end

  def new
    @post = @bulletin.posts.new
  end

  def edit
  end

  def create
    @post = @bulletin.posts.new(post_params)
    @post.user_id = session[:user_id]
    
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
    if @post.user_id != session[:user_id]
      flash[:alert] = "수정 권한이 없습니다."
      redirect_to :back
    end
      if @post.update(post_params)
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @post.user_id != session[:user_id]
      flash[:alert] = "수정 권한이 없습니다."
      redirect_to :back
    end
    @post.destroy
    respond_to do |format|
      format.html { redirect_to bulletin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bulletin
      @bulletin = Bulletin.find(params[:bulletin_id])
    end

    def set_post
      @post = @bulletin.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def bulletin_name(bulletin_id)
    Bulletin.find(bulletin_id).title
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for([@bulletin, @post]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, input_html: { rows: 10 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>

<%= render 'form' %>

<hr>
<%= link_to 'Show', [@post.bulletin, @post], class: 'btn btn-default' %>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<%= render "posts/post_types/#{@bulletin.post_type}" %>

app/views/posts/new.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>

<%= render 'form' %>

<hr>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/posts/show.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>

<table class='table'>
<tr>
  <th>Title</th>
  <td><%= @post.title %></td>
</tr>
<tr>
  <th>UserName</th>
  <td><%= @post.user.username %></td>
</tr>
<tr>
  <th>Content</th>
  <td><%= @post.content %></td>
</tr>
<tr>
  <th>Created at</th>
  <td><%= @post.created_at %></td>
</tr>
</table>

<%= render "comments/comments" %>

<%= link_to 'Edit', edit_bulletin_post_path(@post.bulletin, @post), class: 'btn btn-default' %>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>